version: '1.0.5'
title: 'Brothers in Vines'
author: 'Sherwin Van Wyk'
email: 'brothersinvines@gmail.com'
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brothers-in-vine.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# https://jekyllrb.com/docs/permalinks/

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  products:
    output: true
    permalink: /products/:path
  archives:
    output: true
    permalink: /archives/:path/

social:
  facebook: 'todo'
  instagram: 'brothersinvines'
  tumblr: ''
  twitter: 'todo'

getform:
  uuid: '4717f780-5c3b-4331-9954-d745383c27c7'

menu:
  -
    text: 'Home'
    url: '/'
  -
    text: 'About'
    url: '/about'
  -
    text: 'Contact Us'
    url: '/contact-us'

widgets:
  instagram:
    -
      postID: CAStOSRhRxQ
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-1.jpeg
    -
      postID: CASv8QJh9da
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-2.jpeg
    -
      postID: CC3ApqDpWSt
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-3.jpeg
    -
      postID: CFZo8wBpESZ
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-4.jpeg
    -
      postID: CIV0iutpTMc
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-5.jpeg
    -
      postID: CKxuW2kpCAr
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-6.jpeg

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .idea/

home:
  slideshow:
    -
      title: 'Limitless Blending'
      tagline: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit scelerisque.
      imageURL: assets/brothers-in-vine/images/slideshow/slide-13.png
    -
      title: 'Slide 2'
      tagline: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit scelerisque.
      im ageURL: assets/brothers-in-vine/images/slideshow/slide-24.png
    -
      title: 'Quality Wines'
      tagline: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit scelerisque.
      imageURL: assets/brothers-in-vine/images/slideshow/slide-17.png

stores:
  -
    name: 'Shanghai'
    countrySlug: 'china'
    phone: '+34 (0) 011 0123 012'
    email: 'brothersinvines@gmail.com'
    address: >-
      198 West 21th Street, Suite 721
      Paris 18010
  -
    name: 'South Africa'
    countrySlug: 'south-africa'
    phone: '+27 (0) 83 273 9895'
    email: 'brothersinvines@gmail.com'
    address: >-
      198 West 21th Street, Suite 721
      Paris 18010
