version: '1.0.9'
title: 'Brothers in Vines'
author: 'Sherwin Van Wyk'
email: 'brothersinvines@gmail.com'
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brothersinvines.com" # the base hostname & protocol for your site, e.g. http://example.com
# https://jekyllrb.com/docs/permalinks/

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  products:
    output: true
    permalink: /products/:path
  archives:
    output: true
    permalink: /archives/:path/

social:
  facebook: 'todo'
  instagram: 'brothersinvines'
  tumblr: ''
  twitter: 'todo'

getform:
  uuid: '4717f780-5c3b-4331-9954-d745383c27c7'

menu:
  -
    text: 'Home'
    url: '/'
  -
    text: 'About'
    url: '/about'
  -
    text: 'Contact Us'
    url: '/contact-us'

widgets:
  instagram:
    -
      postID: CAStOSRhRxQ
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-1.jpeg
    -
      postID: CASv8QJh9da
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-2.jpeg
    -
      postID: CC3ApqDpWSt
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-3.jpeg
    -
      postID: CFZo8wBpESZ
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-4.jpeg
    -
      postID: CIV0iutpTMc
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-5.jpeg
    -
      postID: CKxuW2kpCAr
      image_url: assets/brothers-in-vine/images/widgets/instagram/image-6.jpeg

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .idea/

home:
  slideshow:
    -
      title: 'Limitless Blending'
      tagline: >-
        A unique approach to the Wine making Industry
      imageURL: assets/brothers-in-vine/images/slideshow/slide-13.png
    -
      title: 'Family Orientated'
      tagline: >-
        Inclusivity, Ingenuity and Passion for our craft
      imageURL: assets/brothers-in-vine/images/slideshow/slide-24.png
    -
      title: 'Virtual Cellar'
      tagline: >-
        Blend without restrictions
      imageURL: assets/brothers-in-vine/images/slideshow/slide-17.png
    -
      title: 'Founded in 2015'
      tagline: >-
        15 Years of Experience of Dedication and Passion
      imageURL: assets/brothers-in-vine/images/slideshow/slide-15.png
    -
      title: 'Quality & Balance Grapes'
      tagline: >-
        Producing an outstanding wine for you to enjoy
      imageURL: assets/brothers-in-vine/images/slideshow/slide-20.png

stores:
  -
    name: 'China'
    countrySlug: 'china'
    phone: '+86 (0) 150 2680 5630'
    email: 'brothersinvines@gmail.com'
    address: >-
      Shanghai,
      China
  -
    name: 'South Africa'
    countrySlug: 'south-africa'
    phone: '+27 (0) 83 273 9895'
    email: 'brothersinvines@gmail.com'
    address: >-
      Western Cape,
      South Africa
